import { useState } from 'react';
import { useForm, useFieldArray } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { useToast } from '@/hooks/use-toast';
import { apiRequest } from '@/lib/queryClient';
import { 
  Plus, 
  Trash2, 
  Send, 
  Building2, 
  User, 
  Phone, 
  Mail, 
  Calendar, 
  AlertTriangle,
  FileText,
  Package
} from 'lucide-react';
import { insertBorrowingRequestSchema } from '@shared/schema';
import { z } from 'zod';

type BorrowingRequestForm = z.infer<typeof insertBorrowingRequestSchema>;

export default function BorrowingRequest() {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const form = useForm<BorrowingRequestForm>({
    resolver: zodResolver(insertBorrowingRequestSchema),
    defaultValues: {
      centerName: '',
      centerContact: '',
      centerAddress: '',
      requestedItems: [
        {
          itemName: '',
          quantity: 1,
          specifications: '',
          purpose: ''
        }
      ],
      borrowingPurpose: '',
      requestedDate: '',
      expectedReturnDate: '',
      contactPerson: '',
      contactPhone: '',
      contactEmail: '',
      notes: '',
      urgencyLevel: 'Medium'
    },
  });

  const { fields, append, remove } = useFieldArray({
    control: form.control,
    name: "requestedItems",
  });

  // Create borrowing request mutation
  const createBorrowingRequest = useMutation({
    mutationFn: async (data: BorrowingRequestForm) => {
      // Generate document ID
      const timestamp = new Date().toISOString().split('T')[0];
      const documentId = `DOC-BORROW-${timestamp}-${String(Math.floor(Math.random() * 1000)).padStart(3, '0')}`;
      
      // Format the content as a structured document
      const content = `
BORROWING REQUEST

FROM: BONEVET
TO: ${data.centerName}

Contact Information:
- Center: ${data.centerName}
- Address: ${data.centerAddress}
- Contact: ${data.centerContact}
- Contact Person: ${data.contactPerson}
- Phone: ${data.contactPhone || 'N/A'}
- Email: ${data.contactEmail}

Request Details:
- Purpose: ${data.borrowingPurpose}
- Requested Date: ${data.requestedDate}
- Expected Return Date: ${data.expectedReturnDate}
- Urgency Level: ${data.urgencyLevel}

Requested Items:
${data.requestedItems.map((item, index) => `
${index + 1}. ${item.itemName}
   - Quantity: ${item.quantity}
   - Specifications: ${item.specifications || 'N/A'}
   - Purpose: ${item.purpose}
`).join('')}

Additional Notes:
${data.notes || 'None'}

---
Generated by BONEVET Inventory Management System
Date: ${new Date().toLocaleDateString()}
      `.trim();

      return apiRequest('/api/documents', {
        method: 'POST',
        body: JSON.stringify({
          documentId,
          type: 'Borrowing Request',
          title: `Borrowing Request to ${data.centerName} - ${data.requestedDate}`,
          content,
          relatedItemId: data.centerName,
        }),
      });
    },
    onSuccess: () => {
      toast({
        title: 'Borrowing Request Created',
        description: 'The borrowing request has been saved as a document and is ready for processing.',
      });
      queryClient.invalidateQueries({ queryKey: ['/api/documents'] });
      form.reset();
    },
    onError: (error) => {
      toast({
        title: 'Failed to Create Request',
        description: 'Please check your information and try again.',
        variant: 'destructive',
      });
      console.error('Error creating borrowing request:', error);
    },
  });

  const onSubmit = (data: BorrowingRequestForm) => {
    createBorrowingRequest.mutate(data);
  };

  const addItem = () => {
    append({
      itemName: '',
      quantity: 1,
      specifications: '',
      purpose: ''
    });
  };

  const removeItem = (index: number) => {
    if (fields.length > 1) {
      remove(index);
    }
  };

  const getUrgencyColor = (level: string) => {
    switch (level) {
      case 'Critical': return 'destructive';
      case 'High': return 'destructive';
      case 'Medium': return 'default';
      case 'Low': return 'secondary';
      default: return 'default';
    }
  };

  return (
    <div className="container mx-auto py-6 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Borrowing Request</h1>
          <p className="text-muted-foreground">Submit a request to borrow equipment from other centers</p>
        </div>
      </div>

      <Card className="max-w-4xl mx-auto">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Building2 className="h-5 w-5" />
            Create Borrowing Request
          </CardTitle>
          <CardDescription>
            Submit a formal request to borrow equipment from another center. This request will be saved as a document for record keeping.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              {/* Center Information */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="centerName"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="flex items-center gap-2">
                        <Building2 className="h-4 w-4" />
                        Center Name
                      </FormLabel>
                      <FormControl>
                        <Input placeholder="Name of the center you're requesting from" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="urgencyLevel"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="flex items-center gap-2">
                        <AlertTriangle className="h-4 w-4" />
                        Urgency Level
                      </FormLabel>
                      <Select onValueChange={field.onChange} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Select urgency level" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="Low">Low</SelectItem>
                          <SelectItem value="Medium">Medium</SelectItem>
                          <SelectItem value="High">High</SelectItem>
                          <SelectItem value="Critical">Critical</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <FormField
                control={form.control}
                name="centerAddress"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Center Address</FormLabel>
                    <FormControl>
                      <Textarea placeholder="Full address of the center" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="centerContact"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Center Contact Information</FormLabel>
                    <FormControl>
                      <Input placeholder="Main contact number or email for the center" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <Separator />

              {/* Contact Person */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <FormField
                  control={form.control}
                  name="contactPerson"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="flex items-center gap-2">
                        <User className="h-4 w-4" />
                        Contact Person
                      </FormLabel>
                      <FormControl>
                        <Input placeholder="Name of contact person" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="contactPhone"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="flex items-center gap-2">
                        <Phone className="h-4 w-4" />
                        Phone Number
                      </FormLabel>
                      <FormControl>
                        <Input placeholder="Contact phone number" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="contactEmail"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="flex items-center gap-2">
                        <Mail className="h-4 w-4" />
                        Email Address
                      </FormLabel>
                      <FormControl>
                        <Input type="email" placeholder="Contact email address" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <Separator />

              {/* Request Details */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="requestedDate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="flex items-center gap-2">
                        <Calendar className="h-4 w-4" />
                        Requested Date
                      </FormLabel>
                      <FormControl>
                        <Input type="date" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="expectedReturnDate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="flex items-center gap-2">
                        <Calendar className="h-4 w-4" />
                        Expected Return Date
                      </FormLabel>
                      <FormControl>
                        <Input type="date" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <FormField
                control={form.control}
                name="borrowingPurpose"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="flex items-center gap-2">
                      <FileText className="h-4 w-4" />
                      Purpose of Borrowing
                    </FormLabel>
                    <FormControl>
                      <Textarea 
                        placeholder="Describe the purpose and need for borrowing these items"
                        {...field} 
                      />
                    </FormControl>
                    <FormDescription>
                      Provide a detailed explanation of why you need to borrow these items
                    </FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <Separator />

              {/* Requested Items */}
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <Label className="text-base font-medium flex items-center gap-2">
                    <Package className="h-4 w-4" />
                    Requested Items
                  </Label>
                  <Button type="button" variant="outline" size="sm" onClick={addItem}>
                    <Plus className="h-4 w-4 mr-2" />
                    Add Item
                  </Button>
                </div>

                {fields.map((field, index) => (
                  <Card key={field.id} className="p-4">
                    <div className="flex items-center justify-between mb-3">
                      <h4 className="font-medium">Item {index + 1}</h4>
                      {fields.length > 1 && (
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          onClick={() => removeItem(index)}
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      )}
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <FormField
                        control={form.control}
                        name={`requestedItems.${index}.itemName`}
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Item Name</FormLabel>
                            <FormControl>
                              <Input placeholder="Name of the item" {...field} />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />

                      <FormField
                        control={form.control}
                        name={`requestedItems.${index}.quantity`}
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Quantity</FormLabel>
                            <FormControl>
                              <Input
                                type="number"
                                min="1"
                                placeholder="1"
                                {...field}
                                onChange={(e) => field.onChange(parseInt(e.target.value) || 1)}
                              />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                    </div>

                    <div className="grid grid-cols-1 gap-4 mt-4">
                      <FormField
                        control={form.control}
                        name={`requestedItems.${index}.specifications`}
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Specifications (Optional)</FormLabel>
                            <FormControl>
                              <Input placeholder="Brand, model, or specific requirements" {...field} />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />

                      <FormField
                        control={form.control}
                        name={`requestedItems.${index}.purpose`}
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Purpose for This Item</FormLabel>
                            <FormControl>
                              <Textarea 
                                placeholder="How will this specific item be used?"
                                {...field} 
                              />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                    </div>
                  </Card>
                ))}
              </div>

              <Separator />

              {/* Additional Notes */}
              <FormField
                control={form.control}
                name="notes"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Additional Notes (Optional)</FormLabel>
                    <FormControl>
                      <Textarea 
                        placeholder="Any additional information or special requests"
                        {...field} 
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {/* Summary Card */}
              <Card className="bg-muted/50">
                <CardContent className="pt-6">
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="text-sm text-muted-foreground">Request Summary</p>
                      <p className="font-medium">
                        {form.watch('requestedItems')?.length || 0} item(s) requested from {form.watch('centerName') || 'Center'}
                      </p>
                      <div className="flex items-center gap-2 mt-1">
                        <Badge variant={getUrgencyColor(form.watch('urgencyLevel'))}>
                          {form.watch('urgencyLevel')} Priority
                        </Badge>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Submit Button */}
              <div className="flex justify-end">
                <Button
                  type="submit"
                  disabled={createBorrowingRequest.isPending}
                  size="lg"
                  className="min-w-32"
                >
                  {createBorrowingRequest.isPending ? (
                    'Creating...'
                  ) : (
                    <>
                      <Send className="h-4 w-4 mr-2" />
                      Create Request
                    </>
                  )}
                </Button>
              </div>
            </form>
          </Form>
        </CardContent>
      </Card>
    </div>
  );
}